# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(572, 570)
        MainWindow.setStyleSheet("background-color: #2C2F33")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.settings_group = QtWidgets.QGroupBox(self.centralwidget)
        self.settings_group.setGeometry(QtCore.QRect(270, 0, 301, 141))
        self.settings_group.setStyleSheet("color: #8e9297;")
        self.settings_group.setObjectName("settings_group")
        self.wh_url_ph = QtWidgets.QLineEdit(self.settings_group)
        self.wh_url_ph.setGeometry(QtCore.QRect(120, 20, 171, 20))
        self.wh_url_ph.setStyleSheet("color: #dcddde;\n"
"background-color: #40444b;")
        self.wh_url_ph.setObjectName("wh_url_ph")
        self.wh_url = QtWidgets.QLabel(self.settings_group)
        self.wh_url.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.wh_url.setStyleSheet("color: #8e9297;")
        self.wh_url.setObjectName("wh_url")
        self.wh_un_ph = QtWidgets.QLineEdit(self.settings_group)
        self.wh_un_ph.setGeometry(QtCore.QRect(120, 50, 171, 20))
        self.wh_un_ph.setStyleSheet("color: #dcddde;\n"
"background-color: #40444b;")
        self.wh_un_ph.setObjectName("wh_un_ph")
        self.wh_avatar_ph = QtWidgets.QLineEdit(self.settings_group)
        self.wh_avatar_ph.setGeometry(QtCore.QRect(120, 80, 171, 20))
        self.wh_avatar_ph.setStyleSheet("color: #dcddde;\n"
"background-color: #40444b;")
        self.wh_avatar_ph.setObjectName("wh_avatar_ph")
        self.wh_username = QtWidgets.QLabel(self.settings_group)
        self.wh_username.setGeometry(QtCore.QRect(10, 50, 111, 16))
        self.wh_username.setStyleSheet("color: #8e9297;")
        self.wh_username.setObjectName("wh_username")
        self.wh_avatar = QtWidgets.QLabel(self.settings_group)
        self.wh_avatar.setGeometry(QtCore.QRect(10, 80, 111, 16))
        self.wh_avatar.setStyleSheet("color: #8e9297;")
        self.wh_avatar.setObjectName("wh_avatar")
        self.wh_save = QtWidgets.QPushButton(self.settings_group)
        self.wh_save.setGeometry(QtCore.QRect(10, 110, 131, 23))
        self.wh_save.setStyleSheet("QPushButton {\n"
"    background-color: #7f95e3;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #7289DA;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.wh_save.setObjectName("wh_save")
        self.wh_clear = QtWidgets.QPushButton(self.settings_group)
        self.wh_clear.setGeometry(QtCore.QRect(160, 110, 131, 23))
        self.wh_clear.setStyleSheet("QPushButton {\n"
"    background-color: #7f95e3;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #7289DA;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.wh_clear.setObjectName("wh_clear")
        self.sender_group = QtWidgets.QGroupBox(self.centralwidget)
        self.sender_group.setGeometry(QtCore.QRect(0, 140, 571, 411))
        self.sender_group.setStyleSheet("color: #8e9297;")
        self.sender_group.setObjectName("sender_group")
        self.send_title_text = QtWidgets.QLabel(self.sender_group)
        self.send_title_text.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.send_title_text.setStyleSheet("color: #8e9297;")
        self.send_title_text.setObjectName("send_title_text")
        self.send_author_text = QtWidgets.QLabel(self.sender_group)
        self.send_author_text.setGeometry(QtCore.QRect(10, 80, 71, 16))
        self.send_author_text.setStyleSheet("color: #8e9297;")
        self.send_author_text.setObjectName("send_author_text")
        self.send_author_icon_text = QtWidgets.QLabel(self.sender_group)
        self.send_author_icon_text.setGeometry(QtCore.QRect(10, 110, 91, 16))
        self.send_author_icon_text.setStyleSheet("color: #8e9297;")
        self.send_author_icon_text.setObjectName("send_author_icon_text")
        self.send_image_text = QtWidgets.QLabel(self.sender_group)
        self.send_image_text.setGeometry(QtCore.QRect(10, 170, 81, 16))
        self.send_image_text.setStyleSheet("color: #8e9297;")
        self.send_image_text.setObjectName("send_image_text")
        self.send_thumbnail_text = QtWidgets.QLabel(self.sender_group)
        self.send_thumbnail_text.setGeometry(QtCore.QRect(10, 200, 81, 16))
        self.send_thumbnail_text.setStyleSheet("color: #8e9297;")
        self.send_thumbnail_text.setObjectName("send_thumbnail_text")
        self.send_footer_text = QtWidgets.QLabel(self.sender_group)
        self.send_footer_text.setGeometry(QtCore.QRect(10, 230, 47, 13))
        self.send_footer_text.setStyleSheet("color: #8e9297;")
        self.send_footer_text.setObjectName("send_footer_text")
        self.send_timestamp_text = QtWidgets.QLabel(self.sender_group)
        self.send_timestamp_text.setGeometry(QtCore.QRect(10, 290, 61, 16))
        self.send_timestamp_text.setStyleSheet("color: #8e9297;")
        self.send_timestamp_text.setObjectName("send_timestamp_text")
        self.send_title_ph = QtWidgets.QLineEdit(self.sender_group)
        self.send_title_ph.setGeometry(QtCore.QRect(100, 20, 171, 20))
        self.send_title_ph.setStyleSheet("color: #dcddde;\n"
"background-color: #40444b;")
        self.send_title_ph.setObjectName("send_title_ph")
        self.send_author_ph = QtWidgets.QLineEdit(self.sender_group)
        self.send_author_ph.setGeometry(QtCore.QRect(100, 80, 171, 20))
        self.send_author_ph.setStyleSheet("color: #dcddde;\n"
"background-color: #40444b;")
        self.send_author_ph.setObjectName("send_author_ph")
        self.send_author_icon_ph = QtWidgets.QLineEdit(self.sender_group)
        self.send_author_icon_ph.setGeometry(QtCore.QRect(100, 110, 171, 20))
        self.send_author_icon_ph.setStyleSheet("color: #dcddde;\n"
"background-color: #40444b;")
        self.send_author_icon_ph.setObjectName("send_author_icon_ph")
        self.send_image_ph = QtWidgets.QLineEdit(self.sender_group)
        self.send_image_ph.setGeometry(QtCore.QRect(100, 170, 171, 20))
        self.send_image_ph.setStyleSheet("color: #dcddde;\n"
"background-color: #40444b;")
        self.send_image_ph.setObjectName("send_image_ph")
        self.send_thumbnail_ph = QtWidgets.QLineEdit(self.sender_group)
        self.send_thumbnail_ph.setGeometry(QtCore.QRect(100, 200, 171, 20))
        self.send_thumbnail_ph.setStyleSheet("color: #dcddde;\n"
"background-color: #40444b;")
        self.send_thumbnail_ph.setObjectName("send_thumbnail_ph")
        self.send_footer_ph = QtWidgets.QLineEdit(self.sender_group)
        self.send_footer_ph.setGeometry(QtCore.QRect(100, 230, 171, 20))
        self.send_footer_ph.setStyleSheet("color: #dcddde;\n"
"background-color: #40444b;")
        self.send_footer_ph.setObjectName("send_footer_ph")
        self.send_timestamp_cb = QtWidgets.QCheckBox(self.sender_group)
        self.send_timestamp_cb.setGeometry(QtCore.QRect(160, 290, 71, 18))
        self.send_timestamp_cb.setStyleSheet("color: #8e9297;")
        self.send_timestamp_cb.setObjectName("send_timestamp_cb")
        self.send_desc_ph = QtWidgets.QTextEdit(self.sender_group)
        self.send_desc_ph.setGeometry(QtCore.QRect(340, 50, 221, 121))
        self.send_desc_ph.setStyleSheet("color: #dcddde;\n"
"background-color: #40444b;")
        self.send_desc_ph.setObjectName("send_desc_ph")
        self.send_desc_text = QtWidgets.QLabel(self.sender_group)
        self.send_desc_text.setGeometry(QtCore.QRect(280, 50, 61, 16))
        self.send_desc_text.setStyleSheet("color: #8e9297;")
        self.send_desc_text.setObjectName("send_desc_text")
        self.send_color_text = QtWidgets.QLabel(self.sender_group)
        self.send_color_text.setGeometry(QtCore.QRect(280, 20, 61, 16))
        self.send_color_text.setStyleSheet("color: #8e9297;")
        self.send_color_text.setObjectName("send_color_text")
        self.send_color_ph = QtWidgets.QLineEdit(self.sender_group)
        self.send_color_ph.setGeometry(QtCore.QRect(340, 20, 91, 20))
        self.send_color_ph.setStyleSheet("color: #dcddde;\n"
"background-color: #40444b;")
        self.send_color_ph.setReadOnly(True)
        self.send_color_ph.setObjectName("send_color_ph")
        self.send_color_btn = QtWidgets.QPushButton(self.sender_group)
        self.send_color_btn.setGeometry(QtCore.QRect(440, 20, 81, 23))
        self.send_color_btn.setStyleSheet("QPushButton {\n"
"    background-color: #7f95e3;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #7289DA;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.send_color_btn.setObjectName("send_color_btn")
        self.send_send = QtWidgets.QPushButton(self.sender_group)
        self.send_send.setGeometry(QtCore.QRect(10, 350, 271, 23))
        self.send_send.setStyleSheet("QPushButton {\n"
"    background-color: #7f95e3;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #7289DA;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.send_send.setObjectName("send_send")
        self.send_clear = QtWidgets.QPushButton(self.sender_group)
        self.send_clear.setGeometry(QtCore.QRect(290, 350, 271, 23))
        self.send_clear.setStyleSheet("QPushButton {\n"
"    background-color: #7f95e3;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #7289DA;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.send_clear.setObjectName("send_clear")
        self.send_footer_icon_text = QtWidgets.QLabel(self.sender_group)
        self.send_footer_icon_text.setGeometry(QtCore.QRect(10, 260, 91, 16))
        self.send_footer_icon_text.setStyleSheet("color: #8e9297;")
        self.send_footer_icon_text.setObjectName("send_footer_icon_text")
        self.send_footer_icon_ph = QtWidgets.QLineEdit(self.sender_group)
        self.send_footer_icon_ph.setGeometry(QtCore.QRect(100, 260, 171, 20))
        self.send_footer_icon_ph.setStyleSheet("color: #dcddde;\n"
"background-color: #40444b;")
        self.send_footer_icon_ph.setObjectName("send_footer_icon_ph")
        self.send_author_url_ph = QtWidgets.QLineEdit(self.sender_group)
        self.send_author_url_ph.setGeometry(QtCore.QRect(100, 140, 171, 20))
        self.send_author_url_ph.setStyleSheet("color: #dcddde;\n"
"background-color: #40444b;")
        self.send_author_url_ph.setObjectName("send_author_url_ph")
        self.send_author_url_text = QtWidgets.QLabel(self.sender_group)
        self.send_author_url_text.setGeometry(QtCore.QRect(10, 140, 91, 16))
        self.send_author_url_text.setStyleSheet("color: #8e9297;")
        self.send_author_url_text.setObjectName("send_author_url_text")
        self.send_content_text = QtWidgets.QLabel(self.sender_group)
        self.send_content_text.setGeometry(QtCore.QRect(280, 180, 61, 16))
        self.send_content_text.setStyleSheet("color: #8e9297;")
        self.send_content_text.setObjectName("send_content_text")
        self.send_content_ph = QtWidgets.QTextEdit(self.sender_group)
        self.send_content_ph.setGeometry(QtCore.QRect(340, 180, 221, 131))
        self.send_content_ph.setStyleSheet("color: #dcddde;\n"
"background-color: #40444b;")
        self.send_content_ph.setObjectName("send_content_ph")
        self.send_color_clear_btn = QtWidgets.QPushButton(self.sender_group)
        self.send_color_clear_btn.setGeometry(QtCore.QRect(530, 20, 31, 23))
        self.send_color_clear_btn.setStyleSheet("QPushButton {\n"
"    background-color: #7f95e3;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #7289DA;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.send_color_clear_btn.setObjectName("send_color_clear_btn")
        self.send_url_ph = QtWidgets.QLineEdit(self.sender_group)
        self.send_url_ph.setGeometry(QtCore.QRect(100, 50, 171, 20))
        self.send_url_ph.setStyleSheet("color: #dcddde;\n"
"background-color: #40444b;")
        self.send_url_ph.setText("")
        self.send_url_ph.setObjectName("send_url_ph")
        self.send_url_text = QtWidgets.QLabel(self.sender_group)
        self.send_url_text.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.send_url_text.setStyleSheet("color: #8e9297;")
        self.send_url_text.setObjectName("send_url_text")
        self.send_attachment_text = QtWidgets.QLabel(self.sender_group)
        self.send_attachment_text.setGeometry(QtCore.QRect(10, 320, 61, 16))
        self.send_attachment_text.setObjectName("send_attachment_text")
        self.send_attachment_ph = QtWidgets.QLineEdit(self.sender_group)
        self.send_attachment_ph.setGeometry(QtCore.QRect(100, 320, 331, 20))
        self.send_attachment_ph.setStyleSheet("color: #dcddde;\n"
"background-color: #40444b;")
        self.send_attachment_ph.setReadOnly(True)
        self.send_attachment_ph.setObjectName("send_attachment_ph")
        self.send_attachment_btn = QtWidgets.QPushButton(self.sender_group)
        self.send_attachment_btn.setGeometry(QtCore.QRect(440, 320, 81, 23))
        self.send_attachment_btn.setStyleSheet("QPushButton {\n"
"    background-color: #7f95e3;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #7289DA;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.send_attachment_btn.setObjectName("send_attachment_btn")
        self.send_edit = QtWidgets.QPushButton(self.sender_group)
        self.send_edit.setGeometry(QtCore.QRect(10, 380, 271, 23))
        self.send_edit.setStyleSheet("QPushButton {\n"
"    background-color: #7f95e3;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #7289DA;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.send_edit.setObjectName("send_edit")
        self.send_delete = QtWidgets.QPushButton(self.sender_group)
        self.send_delete.setGeometry(QtCore.QRect(290, 380, 271, 23))
        self.send_delete.setStyleSheet("QPushButton {\n"
"    background-color: #7f95e3;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #7289DA;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.send_delete.setObjectName("send_delete")
        self.send_attachment_clear_btn = QtWidgets.QPushButton(self.sender_group)
        self.send_attachment_clear_btn.setGeometry(QtCore.QRect(530, 320, 31, 23))
        self.send_attachment_clear_btn.setStyleSheet("QPushButton {\n"
"    background-color: #7f95e3;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #7289DA;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.send_attachment_clear_btn.setObjectName("send_attachment_clear_btn")
        self.info_group = QtWidgets.QGroupBox(self.centralwidget)
        self.info_group.setGeometry(QtCore.QRect(0, 0, 271, 141))
        self.info_group.setStyleSheet("color: #8e9297;")
        self.info_group.setObjectName("info_group")
        self.info_title = QtWidgets.QLabel(self.info_group)
        self.info_title.setGeometry(QtCore.QRect(10, 20, 191, 31))
        self.info_title.setStyleSheet("font: 87 15pt \"Arial Black\";\n"
"color: #b8bdc2;")
        self.info_title.setObjectName("info_title")
        self.info_version = QtWidgets.QLabel(self.info_group)
        self.info_version.setGeometry(QtCore.QRect(200, 30, 47, 13))
        self.info_version.setStyleSheet("font: 87 10pt \"Arial Black\";\n"
"color: #a7acb0;")
        self.info_version.setObjectName("info_version")
        self.info_author = QtWidgets.QLabel(self.info_group)
        self.info_author.setGeometry(QtCore.QRect(10, 50, 121, 16))
        self.info_author.setStyleSheet("color: #b0b0b0;")
        self.info_author.setObjectName("info_author")
        self.info_import_btn = QtWidgets.QPushButton(self.info_group)
        self.info_import_btn.setGeometry(QtCore.QRect(10, 80, 251, 23))
        self.info_import_btn.setStyleSheet("QPushButton {\n"
"    background-color: #7f95e3;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #7289DA;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.info_import_btn.setObjectName("info_import_btn")
        self.info_export_btn = QtWidgets.QPushButton(self.info_group)
        self.info_export_btn.setGeometry(QtCore.QRect(10, 110, 251, 23))
        self.info_export_btn.setStyleSheet("QPushButton {\n"
"    background-color: #7f95e3;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #7289DA;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.info_export_btn.setObjectName("info_export_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Webhook Sender"))
        self.settings_group.setTitle(_translate("MainWindow", "Webhook Settings"))
        self.wh_url.setText(_translate("MainWindow", "Webhook URL:*"))
        self.wh_username.setText(_translate("MainWindow", "Webhook Username:"))
        self.wh_avatar.setText(_translate("MainWindow", "Webhook Avatar:"))
        self.wh_save.setText(_translate("MainWindow", "Save"))
        self.wh_clear.setText(_translate("MainWindow", "Clear"))
        self.sender_group.setTitle(_translate("MainWindow", "Sender"))
        self.send_title_text.setText(_translate("MainWindow", "Title:"))
        self.send_author_text.setText(_translate("MainWindow", "Author Name:"))
        self.send_author_icon_text.setText(_translate("MainWindow", "Author Icon URL:"))
        self.send_image_text.setText(_translate("MainWindow", "Image URL:"))
        self.send_thumbnail_text.setText(_translate("MainWindow", "Thumbnail URL:"))
        self.send_footer_text.setText(_translate("MainWindow", "Footer:"))
        self.send_timestamp_text.setText(_translate("MainWindow", "Timestamp:"))
        self.send_timestamp_cb.setText(_translate("MainWindow", "True"))
        self.send_desc_text.setText(_translate("MainWindow", "Description:"))
        self.send_color_text.setText(_translate("MainWindow", "Color:"))
        self.send_color_btn.setText(_translate("MainWindow", "Pick"))
        self.send_send.setText(_translate("MainWindow", "Send Message"))
        self.send_clear.setText(_translate("MainWindow", "Clear Fields"))
        self.send_footer_icon_text.setText(_translate("MainWindow", "Footer Icon URL:"))
        self.send_author_url_text.setText(_translate("MainWindow", "Author URL:"))
        self.send_content_text.setToolTip(_translate("MainWindow", "<html><head/><body><p>Simple message content.</p></body></html>"))
        self.send_content_text.setText(_translate("MainWindow", "Content:"))
        self.send_color_clear_btn.setText(_translate("MainWindow", "X"))
        self.send_url_text.setText(_translate("MainWindow", "URL:"))
        self.send_attachment_text.setText(_translate("MainWindow", "Attachment:"))
        self.send_attachment_btn.setText(_translate("MainWindow", "Select"))
        self.send_edit.setText(_translate("MainWindow", "Edit Message"))
        self.send_delete.setText(_translate("MainWindow", "Delete Message"))
        self.send_attachment_clear_btn.setText(_translate("MainWindow", "X"))
        self.info_group.setTitle(_translate("MainWindow", "Info"))
        self.info_title.setText(_translate("MainWindow", "Webhook Sender"))
        self.info_version.setText(_translate("MainWindow", "v0.5.1"))
        self.info_author.setText(_translate("MainWindow", "Made by FrachlitzStudio"))
        self.info_import_btn.setText(_translate("MainWindow", "Import Template"))
        self.info_export_btn.setText(_translate("MainWindow", "Export Template"))
